### PR TITLE
[Feature] Company Locations

### PR DESCRIPTION
**Pull request by chadtomkiss**
Work Done:

- Added migrations to allow companies to have multiple locations
- Removed `location` from `companies` table now that we have a join table

### CODE REVIEW

**Comment by 0xStarcat** [comment]
A good decision 👍

**Comment by jalcine** [comment]
This is dope. Will you be adding models for these? Could place them under `app/models`.

**Comment by chadtomkiss** [comment]
@jalcine Yeah for sure, will start writing the models for the DB schema now that we have it p locked down.

**Comment by chadtomkiss** [comment]
@jalcine Yeah, I think adding the models in a sep PR for all migrations would be better.

**Pull request merged**
