### PR TITLE
[Fix] Database connection

### PR DESCRIPTION
**Pull request by chadtomkiss**
Work Done:

- Added a healthcheck to ensure DB container is running before API container tries to connect.
- Fixed password having `"`'s which caused `DATABASE_URL` to be invalid.
- Fixed `DATABASE_URL` to use `postgres` as the protocol

### CODE REVIEW

**Comment by chadtomkiss** [comment]
@jalcine 👍

**Comment by chadtomkiss** [comment]
Btw, `docker-compose.yml` will parse a `.env` file.

This would allow us to:

1. Move sensitive data out of the repo
2. Re-use variables across containers (i.e user/pass for configuring both postgres & the connection URL)

In the past, I've had a `.env.example` that has the details blank (copied to `.env` using a `Makefile`) allowing the contributor to set their own username/password.

**Comment by jalcine** [comment]
That's a good idea re: leveraging the `.env` file.

**Comment by jalcine** [comment]
I have to remember to add this healthcheck logic to the Dokku instance; lest it'd fail to start.

**Pull request merged**
